config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :posts

   root 'posts#recent'

 get 'post/:id' => 'posts#sidebar'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base

    validates :title, :content, :tag1, :presence => true
	validates :title, :length => {:minimum => 2}
	validates :title, :uniqueness => true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  posts_path
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_admin!, only:[:destroy, :edit, :new, :index, :update]

	def index


		
		@posts = Post.order( "id DESC").all

	end

	

	def show

		@post = Post.find(params[:id])

	end

	

	def new
		
		@post = Post.new

	end

	

	def create

		@post = Post.new(params[:post].permit(:title, :content, :tag1))
		
		if @post.save
			redirect_to posts_path, :notice => "Post saved"

		else
			render "new", :notice => "post not saved!"

		end

	end

	

	def edit

		@post = Post.find(params[:id])

	end

	

	def update

		@post = Post.find(params[:id])

		if @post.update_attributes(params[:post].permit(:title, :content))
			redirect_to posts_path, :notice => "post updated"
		else
			render "edit"
		end

	end

	

	def destroy

		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path, :notice => "post deleted"
	end

	def recent
		
		@posts = Post.order( "id DESC").all

       
		
	end

	def sidebar 

		@posts = Post.order( "id DESC").all

	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% unless notice.nil? %>
<p class="notice"><%= notice %></p>
<% end %>
<% unless alert.nil? %>
<p class="alert"><%= alert %></p>
<% end %>


<%= render 'parts/navBrand' %>
<div class="container">
<div class="row">
			<div class="col-md-9">

			
			<%= yield %>
			
			
			</div>
			
			<div class="col-md-3 sidebar">
					
			</div>
		</div>

</div>




<%= render 'parts/footer' %>

</body>
</html>

app/views/parts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-xs-4 left">
     
        <p>Place sticky footer content here.</p>
    </div>
  
    <div class="col-md-4 col-xs-4 center">
     <p>Created by <i>JustAnotherSmith</i></p>
    </div>
  
    <div class="col-md-4 col-xs-4 right">
        <% if admin_signed_in? %>
     <li>
     <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>        
     </li>
     <% else %>
     <li>
     <%= link_to('Login', new_admin_session_path)  %>  
     </li>
     <% end %>
     </div>
  </div>
</div>

app/views/parts/_navBrand.html.erb
<div class="container">
	<div class="row nav-row">
		<div class="col-xs-8 col-md-8  left">
			<h1>Title goes here</h1>
		</div>
		<div class="col-xs-4 col-md-4 right">
		<%= link_to image_tag("facebook.png", :alt => "facebook"), "http://www.facebook.com" %>
		<%= link_to image_tag("twitter.png", :alt => "twitter"), "http://www.twitter.com" %>
		<%= link_to image_tag("pinterest.png", :alt => "pinterest"), "http://www.pinterest.com" %>

		</div>






	</div>
</div>

app/views/parts/_sidebar.html.erb
<h4>previous posts</h4>
			<% @posts.each do |post| %>
			<p><%= link_to post.title, post %></p>
			<p><%= post.tag1 %></p>
			<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @post do |form| %>
<p>
<%= form.label :title %><br/>
<%= form.text_field :title %>
</p>
<p>
<%= form.label :content %><br/>
<%= form.text_area :content %>
</p>
<p>
<%= form.submit "save post" %>

</p>

<% end %>

app/views/posts/index.html.erb


<% @posts.each do |post| %>
	<h2><%= link_to post.title, post %></h2>
	<p><%= post.content %></p>
	<p>
		<%= link_to "edit", edit_post_path(post) %> |
		<%= link_to "Delete", post, :data => {:confirm => "Are you sure?"}, :method => :delete %>

		

	</p>
	<hr/>

<% end %>

<p><%= link_to "Add a new post", new_post_path %></p>

app/views/posts/new.html.erb
<h1>Add a new post</h1>

<%= form_for @post do |form| %>
<% if @post.errors.any? %>
<h2>Errors:</h2>
<ul>
<% @post.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
</ul>
<% end %>
<p>
<%= form.label :title %><br/>
<%= form.text_field :title %>
</p>
<p>
<%= form.label :tag %><br/>
<%= form.text_field :tag1 %>
</p>
<p>
<%= form.label :content %><br/>
<%= form.text_area :content %>
</p>
<p>
<%= form.submit "Add post" %>

</p>


<% end %>

app/views/posts/recent.html.erb
	
		<div class="row">
			<div class="col-md-9">

			
			<h2><%= @posts.first.title %></h2>
			<p>#<%= @posts.first.tag1 %></p>
			<small><%= @posts.first.created_at.strftime("%B %d, %Y") %></small>
			<p><%= @posts.first.content %></p>
			<hr/>
			
			
			</div>
			
			<div class="col-md-3 sidebar">
			<h4>previous posts</h4>
			<% @posts.each do |post| %>
			<p><%= link_to post.title, post %></p>
			<p><%= post.tag1 %></p>
			<% end %>
			</div>
		</div>

	



app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<small><%= @post.created_at %></small>

app/views/posts/sidebar.html.erb
<h4>previous posts</h4>
			<% @posts.each do |post| %>
			<p><%= link_to post.title, post %></p>
			<p><%= post.tag1 %></p>
			<% end %>
			